{% set name = "cfitsio" %}
{% set version = "4.6.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/{{ name }}-{{ version }}.tar.gz  # [not win]
  sha256: fad44fff274fdda5ffcc0c0fff3bc3c596362722b9292fc8944db91187813600                  # [not win]
  url: https://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/cfit-{{ version }}.zip           # [win]
  sha256: 03096642e79f8848d4f75676e40091f7ea4f783d844aa42b316806ebb2b3d075                  # [win]
  patches:
    - 0001-fix-include-order.patch  # [win]

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('cfitsio', max_pin='x.x.x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake <4
    - ninja-base
  host:
    - libcurl {{ libcurl }}
    - bzip2 {{ bzip2 }}
    - zlib {{ zlib }}

test:
  commands:
    # UNIX
    - test -f ${PREFIX}/lib/libcfitsio{{ SHLIB_EXT }}  # [unix]
    - test -f ${PREFIX}/lib/cmake/cfitsio/cfitsioConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/cfitsio/cfitsioConfigVersion.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/cfitsio/cfitsioTargets-release.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/cfitsio/cfitsioTargets.cmake  # [unix]
    - test -f ${PREFIX}/lib/pkgconfig/cfitsio.pc  # [unix]
    - test -f ${PREFIX}/include/cfitsio_export.h  # [unix]
    - test -f ${PREFIX}/include/fitsio.h  # [unix]
    - test -f ${PREFIX}/include/fitsio2.h  # [unix]
    - test -f ${PREFIX}/include/longnam.h  # [unix]
    - test -f ${PREFIX}/bin/cookbook  # [unix]
    - test -f ${PREFIX}/bin/fitscopy  # [unix]
    - test -f ${PREFIX}/bin/fitsverify  # [unix]
    - test -f ${PREFIX}/bin/fpack  # [unix]
    - test -f ${PREFIX}/bin/funpack  # [unix]
    - test -f ${PREFIX}/bin/imcopy  # [unix]
    - test -f ${PREFIX}/bin/smem  # [unix]
    - test -f ${PREFIX}/bin/speed  # [unix]
    # WIN
    - if not exist %LIBRARY_LIB%\cfitsio.lib exit 1  # [win]
    - if not exist %LIBRARY_LIB%\cfitsio.lib exit 1  # [win]
    - if not exist %LIBRARY_LIB%\cmake\cfitsio\cfitsioConfig.cmake exit 1  # [win]
    - if not exist %LIBRARY_LIB%\cmake\cfitsio\cfitsioConfigVersion.cmake exit 1  # [win]
    - if not exist %LIBRARY_LIB%\cmake\cfitsio\cfitsioTargets-release.cmake exit 1  # [win]
    - if not exist %LIBRARY_LIB%\cmake\cfitsio\cfitsioTargets.cmake exit 1  # [win]
    - if not exist %LIBRARY_LIB%\pkgconfig\cfitsio.pc exit 1  # [win]
    - if not exist %LIBRARY_BIN%\cfitsio.dll exit 1  # [win]
    - if not exist %LIBRARY_BIN%\cookbook.exe exit 1  # [win]
    - if not exist %LIBRARY_BIN%\fitscopy.exe exit 1  # [win]
    - if not exist %LIBRARY_BIN%\fitsverify.exe exit 1  # [win]
    - if not exist %LIBRARY_BIN%\fpack.exe exit 1  # [win]
    - if not exist %LIBRARY_BIN%\funpack.exe exit 1  # [win]
    - if not exist %LIBRARY_BIN%\imcopy.exe exit 1  # [win]
    - if not exist %LIBRARY_BIN%\speed.exe exit 1  # [win]
    - if not exist %LIBRARY_INC%\cfitsio_export.h exit 1  # [win]
    - if not exist %LIBRARY_INC%\fitsio.h exit 1  # [win]
    - if not exist %LIBRARY_INC%\fitsio2.h exit 1  # [win]
    - if not exist %LIBRARY_INC%\longnam.h exit 1  # [win]
    
  # Downstream tests are not possible due to cfitsio being pinned to a specific
  # major.minor.patch version in conda-forge-pinning. E.g. gdal is currently
  # build pinned against cfitsio 4.0.0, which means we cannot test a new version
  # of cfitsio (4.1.0 say) in a downstream test of gdal.
  # Downstream tests could be enabled again if there are no foreseeable new versions
  # cfitsio.
  # downstreams:
  #   - gdal  # [x86_64]

about:
  home: https://heasarc.gsfc.nasa.gov/fitsio/fitsio.html
  license: LicenseRef-fitsio
  license_family: Other
  license_file: licenses/License.txt
  summary: "A library for reading and writing FITS files"
  description: |
    CFITSIO is a library of C and Fortran subroutines for reading and writing
    data files in FITS (Flexible Image Transport System) data format. CFITSIO
    provides simple high-level routines for reading and writing FITS files that
    insulate the programmer from the internal complexities of the FITS format.
    CFITSIO also provides many advanced features for manipulating and filtering
    the information in FITS files.
  dev_url: https://github.com/HEASARC/cfitsio
  doc_url: https://heasarc.gsfc.nasa.gov/docs/software/fitsio/quick/quick.html

extra:
  recipe-maintainers:
    - pkgw
    - teake
