{% set name = "cfitsio" %}
{% set version = "3.420" %}
{% set nodotversion = version | replace('.', '') %}
{% set sha256 = "6c10aa636118fa12d9a5e2e66f22c6436fb358da2af6dbf7e133c142e2ac16b8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}{{ nodotversion }}.tar.gz
  url: ftp://heasarc.gsfc.nasa.gov/software/fitsio/c/{{ name }}{{ nodotversion }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - ldflags.patch

build:
  number: 0
  detect_binary_files_with_prefix: true
  skip: true  # [win]

requirements:
  build:
    - toolchain

test:
  commands:
    - test -f ${PREFIX}/lib/libcfitsio.so  # [linux]
    - test -f ${PREFIX}/lib/libcfitsio.dylib  # [osx]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://heasarc.gsfc.nasa.gov/fitsio/fitsio.html
  license: fitsio
  license_file: License.txt
  summary: "A library for reading and writing FITS files"

extra:
  recipe-maintainers:
    - pkgw
