# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ITAb47GvV9Yo7N8VFUC/3ZlN5sqyOZBNpx4zm7vE8JTZ43Iav4tAln+Q6Qx9YTHmwIQ1BkeeCxhPFhBXv6nFntHpI74SbeP/n++UfH6Svo9lJAP0mrn+irSTLz5+dGbjH7hpDgQ+PFFFi3vZyqOBG60q4WG66l/mb4iutQk1nWMMtKrZPW/HRTp9WJNjXm+2Y+9nfadyUfMEgqMgeL/bTnea2BnIYE6OOYz1Qechwv1aU4IkaWp2zRvm6F2z4+ArJS3MxKDu4GOfKhZ3W1aoOdhPVd8iANXYM93kzrjWLIJogPF7LM/vrxaYGQ/H1Fok9V0hVhohthJZIaH3t3ILU50DMvav/Tzy0MLkvfiw3jB/I46h/Gn0/bg9mMg/5/3mBJcO7LqcNnhfhm5/R6rar/vuCdfv5lxsRcC4gedsBuXgll3gxRU/FECZkEKIZLufSm7hS+Z7ynrpbDZ9UQTtLY6NRO/GzSOBDEgWiXHTcBX9OhP7ENf5PYjQmaLd0TWAP54OOL+moAtrmitpn1xnzP7X0F5f3BYGVp6v9leCDtp5Yq/hnQRx2iyvdS9aA5gcfQax0bn6Ny8PpsCyn/I1aH96Gm7P1M9fSNjG9N2rj628sI6qSynD/5Ox+j+TlYVA/Egnv8QA8XqNbW7R+SQ3wxKJCbZna/ztUSz4j0oRh9Q="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
