travis:
  secure:
    BINSTAR_TOKEN: ITAb47GvV9Yo7N8VFUC/3ZlN5sqyOZBNpx4zm7vE8JTZ43Iav4tAln+Q6Qx9YTHmwIQ1BkeeCxhPFhBXv6nFntHpI74SbeP/n++UfH6Svo9lJAP0mrn+irSTLz5+dGbjH7hpDgQ+PFFFi3vZyqOBG60q4WG66l/mb4iutQk1nWMMtKrZPW/HRTp9WJNjXm+2Y+9nfadyUfMEgqMgeL/bTnea2BnIYE6OOYz1Qechwv1aU4IkaWp2zRvm6F2z4+ArJS3MxKDu4GOfKhZ3W1aoOdhPVd8iANXYM93kzrjWLIJogPF7LM/vrxaYGQ/H1Fok9V0hVhohthJZIaH3t3ILU50DMvav/Tzy0MLkvfiw3jB/I46h/Gn0/bg9mMg/5/3mBJcO7LqcNnhfhm5/R6rar/vuCdfv5lxsRcC4gedsBuXgll3gxRU/FECZkEKIZLufSm7hS+Z7ynrpbDZ9UQTtLY6NRO/GzSOBDEgWiXHTcBX9OhP7ENf5PYjQmaLd0TWAP54OOL+moAtrmitpn1xnzP7X0F5f3BYGVp6v9leCDtp5Yq/hnQRx2iyvdS9aA5gcfQax0bn6Ny8PpsCyn/I1aH96Gm7P1M9fSNjG9N2rj628sI6qSynD/5Ox+j+TlYVA/Egnv8QA8XqNbW7R+SQ3wxKJCbZna/ztUSz4j0oRh9Q=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
