travis:
  secure:
    BINSTAR_TOKEN: OGMvfi/UYsQVFYy7v/hxwTWFMAT07eZ9cD3W2SBq0ZVSLvlqBq2tiV+0ZKoWulHWUzM7Vxdy/Ru96EK8aknNDO1f+kQblwr02+ZTwjZh0y1nw6cFISnL9+ov9DmitOBx7pOz9FiguHEJAmafBIXYcaGUSLACpT9N3irDGNLp2xGE1iGL2LncZs1ef5goVDeR5fKVDwtJ/NQp/COJqOvhm1Msrmh9tGXJD6qGY4BMR4YtWoGoEzNqLS6xEgVwllGSKm7Fz9mTrv6TwS9BMoWaP1rYoPlbxcaEF/GL3saRooqGCegnY1b+yjDVLmsILmYYSs1qgSYKNjhiogZGWT3OAlXaxLclYZduIQegxbyMbbFyoswr3yjJoxhR64HI8vrOSV+zljlUckEGZhBKSoca8XXEEfvNRdIMIKYmmwf/VoVyOv4L6DQ0EfgMrW4fzaTQfuUH5rJeEZi6/Zniqkzrv0kvZ/cFCq1s+u+zAnPwfxZniduzMPy9xQquUuTgkYgm1p/YLVum+SIbUT77z8uTH9CyKR0q+IU2e178dgazlI3jOobkjrTR98oxKR386uERWtET+2ifcvoCS1moplQvnTim5Wpt4IN+owkvff5qEVQoDPiu2kgra3XSwxzoAjPmKH1SUDowWABHVSCor8pM3GFL4u+3ik6F/No0bxCZ8zY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
