travis:
  secure:
    BINSTAR_TOKEN: nk8+h4CcItBuczA35N98Lszm6sEAEW+KUc0nAsD8d8xZJB98z5Jb066TDNQfwb1kgIMRVW+kKOQIp2Q6uUqoCYO2tH3wq/UKzi7k518YRBndbQUrVLjVFtAqKwAifJeCp3r6ybe7fZ9z0jD+HKuxmYEuh8cDIPt89PVxIR4O/7KP/jQbh/YaZAOOrbASmiGXeKnQTWcfpHQ9SfVu555ek6mJs9GTfZD0O+RUhET4xaBhmmEGXQLk28DcpVTbtFRbCWWzahmXJq0nBxLAWwBkmlx4FPKJ/Ezse7qGnA+OcKzBP94zx4s+Lx/klkvTJ7DaGK3aNw+/+Yq/1lZv1KZUvS9ovsJSkdeCOVSx1zn5Rcw7dlxF/GFKFYa0HmXDCOymW3AGI4iaVOVyPJ+4WjNUbpVXfx+/jcYQwwidUhU1ciQleaCVo2p4khCI/adv0JfCIQUrerCBLx/11Tw391948g17R9Cj9OKDzk0AH1C1Q195j07zuRBcWysQt2um26icSZMrzveKX+ddgSkAYqdFx2+TZg4zZN6CcK9UjXrcQa15F0h7tBvnNfYBE5lRmluAaUPyNq9H7PnvQhegXGVEsZkgsq6A3dPhXQ11tKsYNePDm7DwuiVSGClf7VlclUDUokkoe3lgcSnTNSfsoEp7HzW7WoEHpXd+tkX12V5eo9Y=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
