travis:
  secure:
    BINSTAR_TOKEN: wXVdyo37/Gqz50E7spd7fiMJCxNch6tY9wzsiSseESRMJMI4cmkNCnTN156rNlHv+YYKW3DixeB1sBO9K1CoD0tZu7rcKy1IerRgOCVD0pn3xnTH2Bnb3emNyhk2M1Kq0HGqZ8Xgsn+/iSRbZUu8NieHRbaUSXbihFmT2E2APR8l2+72PWE/M4V8rktsyQgBMvFsGAFiRSVWmS9ZYVq8GspTYBxa2Rqam1mS72WYLxwVxGwHAuzkfcXXGa/wtFnRmAhBl9MWiJI/R4UmLSg0y9d82MGDpvLvo2CVMmfQkslYtD3lBWWToXvZIb42+/3FH5NTXmfNAxVa3alagNE9gEKYeD2Oo4+i0xlLdoYSoolACLWpeNnyqVhrVv0bShSAkxYcoo/GuO/X+2IxoGwDWOY9PTogceLrmjmPlErOXvhIq09YLsvNYlDUL75Yd7xP6MzjLBLQv9bKzmC0dsEigSl4fd3Y0ZDa1mjN8qLJEgKX/9DmHaqbPRxk0P/XEtoto3J+IUr9+FgbFdwSiIprn4PTOaZ6OgDlOPkF4eHA64mnLM2gLPjt99xLEUeu5WQsGEW9Gdt4Nfz83zrJGVm1GoKw6ahGU1dgTb3t9xp8i+Q78fm+C8I3UWw4+QPy2H0KDUI7YU7xMbH8bYckN0JgYpNx5hKrhy75dgZ1s14Drjc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
