appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: qiAjc3X3pWzkYHa3hJ3cE01xdGtPu5nW+YqttQ1qS3gqlJu9yXz6hFgNqr0uUT0lr6Z+Tqeeo8pbT1yGUZ7z5TIwLMj4lylgRMh6qv1/GxE8duWELemnKwfnU+7mzXXH6kcWyflP4vMF5uHsISvVRoWqub7F/NxsLQ4pRZr9/CYmnHqzi27HirngxtpH+vhI26rrMFhOkK5HH5CNbAUEh0kX6HPvrllNfo1Zx4wZ528hj9pDC7tSV/Saqk2WOYGTbZVmJwpOBM7iTyCIi67EVeuS2R+ig9lBIQE4lqNL2IhrKa74cDHZsVEjukyUTF4+XZgkfY+tFb1XWv4A9gnrp1owYctI8mEGXDJxWISdaKWT/njEjTsxyaoAN1O0LaZUFro8ScFmTIwn3EHZOdxcqtM+3mBVdL3G1wibV5Bnb6u2j63VmnPmWJlTm5TTsrRE+9z9dkOonhE98BDtB8KGeRdpB92GwpQPj7Cccm7N8Xc2SYr3EW5S8pUtVmuZpGtudFs9c2LyTK+AJkhjxj9aZcfuE1P8oo3E4c/i6wVjk1AFVZkLp4ZiWyYDLdbPYr2BptKJP5JPAXQov9/Vaj6UKwahbtjsBSlLQ9Cd3Cxfa1XPx31cEde1l9Rz0LvaKLJZZAd19bSea8Z+IICI3Os5j4rcwOn0PF3gP9JZdPyxbQ4=}
